version: '3'
services:
  app:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    container_name: my-rails-app
    depends_on:
    - postgres
    env_file:
    - .docker-development.env
    ports:
    - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/app

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  test:
    build: .
    command: bundle exec guard start --no-bundler-warning --no-interactions
    container_name: my-rails-test
    depends_on:
    - postgres
    env_file:
    - .docker-test.env
    stdin_open: true
    tty: true
    volumes:
      - .:/var/app

volumes:
  pg_data:
