version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
    - "27020:27017"
    volumes:
    - mongo_data:/data/db

  mongotest:
    image: mongo:latest
    command: mongod --storageEngine ephemeralForTest
    ports:
      - "27017"

  app:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    container_name: my-rails-app
    depends_on:
    - mongo
    env_file:
    - .docker-development.env
    ports:
    - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - bundled_gems:/bundler
      - .:/var/app

  test:
    build: .
    command: bundle exec guard start --no-bundler-warning --no-interactions
    container_name: my-rails-test
    depends_on:
    - mongotest
    env_file:
    - .docker-test.env
    stdin_open: true
    tty: true
    volumes:
      - bundled_gems:/bundler
      - .:/var/app

volumes:
  bundled_gems:
  mongo_data:
